import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./layout/header/header";
import { Footer } from "./layout/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
    
      <body className={inter.className}>
      <div className="h-screen flex flex-col justify-between">
     <div>
      <Header />
       <div className="container">
         <div className="flex">
           <div className="w-full flex justify-center bg-[#dbe2e448]  h-[100vh]">
               {children}
           </div>
           </div>
         </div>
      </div>
     <Footer />
   </div>
        </body>

    </html>
  );
}


